POST http://localhost:3000/clients HTTP/1.1
Content-Type: application/json

{
    "name": "Jhon Doe",
    "email": "jhon@joa.com"
}


###

POST http://localhost:3000/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "6b9dffb9-d9f7-4ed6-8d4c-5bc10e8827bc"
}


###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "6b9dffb9-d9f7-4ed6-8d4c-5bc10e8827bc",
    "account_id_to": "303bc8c1-9957-4e51-9f18-e0d5b95207e7",
    "amount": 12
}